### ISSUE TITLE
Issue after generating a project with cli 

### ISSUE THREAD

**Issue by futureslasher** [typeix/typeix#2]
This error when trying to start the generated project or starting it in watch mode 

hopefully you can help 

[04:04:29.764] [InstallHandler] No installation found
   ^

SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by futureslasher** [comment]
CMD @igorzg

**Comment by igorzg** [comment]
@futureslasher ok let me try

**Comment by igorzg** [comment]
@futureslasher thank you, I will resolve it ASAP 👍

**Comment by futureslasher** [comment]
@igorzg  Thank you for your help and thanks for mainting this fabulous framework

**Comment by igorzg** [comment]
@futureslasher it works as well in power shell
![node-12 16 2](https://user-images.githubusercontent.com/1614531/136708102-43e2c55d-d716-42e1-9602-e929e5ce3631.png)

**Comment by futureslasher** [comment]
@igorzg  thank you for the fast investigation , how to init it with ts ?

**Comment by futureslasher** [comment]
@igorzg  can we expect a fast resolve for the bug

**Comment by igorzg** [comment]
` typeix new project-name` without specifying -l

**Comment by igorzg** [comment]
@futureslasher I will resolve issue tomorrow.

**Comment by igorzg** [comment]
@futureslasher it's actually pretty quick fix so I've published new update. You will need to delete your current demo project.

`Update to @typeix/cli version 8.1.2`
delete your current project
`typeix new demo-js -l js`
start your project
`cd demo-js`
`yarn start:dev`
![node-12 16 2](https://user-images.githubusercontent.com/1614531/136710581-90132abb-b6b0-4bf1-a405-19b0439eaf17.png)

**Comment by igorzg** [comment]
@futureslasher  thank you for reporting issue, let me know if something didn`t work

**Comment by igorzg** [comment]
@futureslasher btw issue was only if you initalized project with javascript, but if you initalized project as typescript everything was ok.

![node-12 16 2](https://user-images.githubusercontent.com/1614531/136711386-532ae42d-3eca-4f87-8217-e0cedac5f9c9.png)
in your case you made error in code `:`.
![node-12 16 2](https://user-images.githubusercontent.com/1614531/136711415-f21b833c-a6f4-41fd-b81c-2c1942a1eed8.png)
just recreate demo project and everything should be fine.

**Comment by futureslasher** [comment]
yarn build built the framework successfully but yarn start fails with the previous error

**Comment by futureslasher** [comment]
@igorzg  update now the js version is working but typescript does not work and still displays the same error

**Comment by igorzg** [comment]
@futureslasher please push your version of code to git, so I can see where is error.

**Comment by igorzg** [comment]
@futureslasher Other option is that you install nvm  https://github.com/coreybutler/nvm-windows and try with other version let's say node 14, because that must be something with your environment
